POST http://localhost:3001/api/userstories/61b720b90df31200168affb7/tasks
Content-Type: application/json
Authorization: bearer add-bearer-here

{
    "name": "New task test new 4",
    "status": "waiting"
  }

