POST http://localhost:3001/api/sprintbacklogs/6108e0e1d5d24b436e2227de/stories
Content-Type: application/json

{
    "tasks": [],
    "story": "new story test",
    "date": "2021-08-10T05:22:20.625Z",
    "status": "testi",
    "priority": 123,
    "id": "61120d0cdd0d4f1797aefe8f"
  }

