name: Push to main

on:
  push:
    branches:
      - main

jobs:
  push_to_main:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install frontend
        run: | 
          cd frontend
          npm install
      - name: npm test frontend
        run: | 
          cd frontend
          CI=true npm test
      - name: npm install backend
        run: | 
          cd backend
          npm install
      - name: npm test backend
        run: | 
          cd backend
          CI=true npm test